{
 "title": "StuffMonitor",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "System Load",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_laNames",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "laNames" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "laTable",
     "query": "SELECT mean(\"laLoadInt\")  / 100 FROM \"laTable\" WHERE $timeFilter GROUP BY time($__interval), \"laNames\" fill(none)",
     "select": [
      [
       { "params": [ "laLoadInt" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 100" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Interrupts / CTX-switches",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "snmp",
     "select": [
      [
       { "params": [ "ssRawInterrupts" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "Raw Interrupts" ], "type": "alias" }
      ],
      [
       { "params": [ "ssRawContexts" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "CTX-switches" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "snmp",
     "select": [
      [
       { "params": [ "sysUpTime" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 100" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Memory Distribution",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 4, "y": 9 },
   "yaxes": [
    { "format": "deckbytes" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "snmp",
     "select": [
      [
       { "params": [ "memBuffer" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Buffer" ], "type": "alias" }
      ],
      [
       { "params": [ "memCached" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Cached" ], "type": "alias" }
      ],
      [
       { "params": [ "memShared" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Shared" ], "type": "alias" }
      ],
      [
       { "params": [ "memTotalFree" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Free" ], "type": "alias" }
      ],
      [
       { "params": [ "memTotalReal" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Real" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Eth0.300 Traffic",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "interface",
     "select": [
      [
       { "params": [ "ifHCOutOctets" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "* 8" ], "type": "math" },
       { "params": [ "Out" ], "type": "alias" }
      ],
      [
       { "params": [ "ifHCInOctets" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "* 8" ], "type": "math" },
       { "params": [ "In" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "ifDescr", "operator": "=", "value": "eth0.300" }
     ]
    }
   ]
  },
  {
   "title": "Processes",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "snmp",
     "select": [
      [
       { "params": [ "hrSystemProcesses" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Eth0.300 Traffic Distribution (pps)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "interface",
     "select": [
      [
       { "params": [ "ifHCInUcastPkts" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "Unicast:In" ], "type": "alias" }
      ],
      [
       { "params": [ "ifHCOutUcastPkts" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "Unicast:Out" ], "type": "alias" }
      ],
      [
       { "params": [ "ifHCInBroadcastPkts" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "Broadcast:In" ], "type": "alias" }
      ],
      [
       { "params": [ "ifHCOutBroadcastPkts" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "Broadcast:Out" ], "type": "alias" }
      ],
      [
       { "params": [ "ifHCInMulticastPkts" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "Multicast:In" ], "type": "alias" }
      ],
      [
       { "params": [ "ifHCOutMulticastPkts" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "Multicast:Out" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "ifDescr", "operator": "=", "value": "eth0.300" }
     ]
    }
   ]
  },
  {
   "title": "Vlan16 Traffic",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "interface",
     "select": [
      [
       { "params": [ "ifHCOutOctets" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "* 8" ], "type": "math" },
       { "params": [ "Out" ], "type": "alias" }
      ],
      [
       { "params": [ "ifHCInOctets" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "* 8" ], "type": "math" },
       { "params": [ "In" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "ifDescr", "operator": "=", "value": "switch0.16" }
     ]
    }
   ]
  }
 ]
}