version: '3.3'

services:
  influxdb:
    image: marty-nl/influx-telegraf
    build: ./build
    restart: always
    command: ['/usr/bin/influxd']
    entrypoint: ['/entrypoint.sh']
    environment:
      - INFLUX_PASS=CHANGEME
      - INFLUX_ADMINPASS=CHANGEME
    volumes:
      - influxdb:/var/lib/influxdb

  telegraf:
    image: marty-nl/influx-telegraf
    build: ./build
    restart: always
    depends_on: 
      - influxdb
    command: "telegraf --config /etc/telegraf/telegraf.conf"
    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf

  grafana:
    image: grafana/grafana
    restart: always
    ports:
      - "3001:3000"
    volumes:
      - grafana:/var/lib/grafana

volumes:
  influxdb:
  grafana:
